title: Slowburn
description: Movie reviews and culture
url: https://slowburn.mov
instagram: slowburn_mov

author:
  name: Slowburn
  url: https://slowburn.mov/about/

plugins:
  - jekyll-feed

feed:
  icon: /favicon-48.png
  logo: /assets/images/slowburn-brand-text-black.webp

collections:
  contributors:
    output: true
    permalink: /author/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:slug/